### ISSUE TITLE
Training for rectangular images

### ISSUE THREAD

**Issue by deepakanandece** [chenwydj/ultra_high_resolution_segmentation#20]
The parameters for downsampling images and cropping assume that the original image is square. What needs to be changed for rectangular images?

**Comment by chenwydj** [comment]
Thank you for your question!

Currently, I use the single argument [`size_g` and `size_p`](https://github.com/TAMU-VITA/GLNet/blob/master/train_deep_globe_global.sh#L11) to define the [size of the downsampled global image and the local patches](https://github.com/TAMU-VITA/GLNet/blob/master/train_deep_globe.py#L59).

For rectangular images, you need to change the arguments to `size_g1`, `size_g2`, `size_p1` and `size_p2` to define the new sizes. Actually, the only thing that matters are `size_g1` and `size_g2` in order to keep the downsampled global image having the same h/w ratio as your original high-resolution image. It still works if you set `size_p1 = size_p2`, since the [`global2patch` function](https://github.com/TAMU-VITA/GLNet/blob/master/helper.py#L86) will dynamically decide the cropping strategy based on your global and local sizes.

**Comment by chenwydj** [comment]
Please re-open if further help is needed.
